<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $terms
 * @var bool $totals
 * @var string $resourceName
 * @var array $args
 * @var string $type
 */

$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
$api = $this->plugin('api');
$siteSlug = $this->params()->fromRoute('site-slug');

$references = $this->plugin('references');

$this->htmlElement('body')->appendAttribute('class', 'reference browse list');
?>

<ul class="references">
    <?php foreach ($terms as $term): ?>
    <li><?php
    // TODO Currently, the totals are determined one by one.
    if ($totals):
        // TODO Get the properties labels one time.
        $element = $api->searchOne($type, ['term' => $term])->getContent();
        $total = $references->count([$term], $args['query'], ['resource_name' => $resourceName]);
        $total = reset($total);
        echo $hyperlink(
            sprintf($translate('%s (%d)'), $element->label(), $total),
            // TODO Define the link to the reference page.
            $url('site/page', ['site-slug' => $siteSlug, 'page-slug' => str_replace(':', '-', $term)]),
            ['title' => sprintf($translate('Browse %s'), $element->label())]
        );
    else:
        $element = $api->searchOne($type, ['term' => $term])->getContent();
        $total = $references->count([$term], $args['query'], ['resource_name' => $resourceName]);
        echo $hyperlink(
            $element->label(),
            // TODO Define the link to the reference page.
            $url('site/page', ['site-slug' => $siteSlug, 'page-slug' => str_replace(':', '-', $term)]),
            ['title' => sprintf($translate('Browse %s'), $element->label())]
        );
    endif;
    ?>
    </li>
    <?php endforeach; ?>
</ul>
