<?php
if (count($subjects)):
    // $resourceName = 'items';
    $controllerName = 'item';
    $queryType = isset($options['query_type']) ? $options['query_type'] : $this->setting('reference_query_type', 'eq');
    $expanded = isset($options['expanded']) ? $options['expanded'] : $this->setting('reference_tree_expanded');
    // Dublin Core Subject is always 3.
    $referenceId = 3;
    $this->headLink()->appendStylesheet($this->assetUrl('vendor/jquery-simplefolders/main.css', 'Reference'));
    $this->headScript()->appendFile($this->assetUrl('vendor/jquery-simplefolders/main.js', 'Reference'));
?>
<div id="reference-headings">
    <ul class="tree">
        <?php
            // Create the tree.
            $previous_level = 0;
            foreach ($subjects as $key => $subject) {
                $first = substr($subject, 0, 1);
                $space = strpos($subject, ' ');
                $level = ($first !== '-' || $space === false) ? 0 : $space;
                $subject = trim($level == 0 ? $subject : substr($subject, $space));

                // Close the previous line (done before, because next line is
                // not known yet).
                if ($key == 0) {
                    // Nothing for the first level.
                }
                elseif ($level > $previous_level) {
                    // Deeper level is always the next one.
                }
                // Higher level.
                elseif ($level < $previous_level) {
                    echo '</li>' . PHP_EOL . str_repeat('</ul></li>' . PHP_EOL, $previous_level - $level);
                }
                // First line, deeper or equal level.
                else {
                    echo '</li>' . PHP_EOL;
                }

                // Start the line with or without a new sub-list.
                if ($level > $previous_level) {
                    // Deeper level is always the next one.
                    echo PHP_EOL . '<div class="expander' . ($expanded ? ' expanded' : '') . '"></div>';
                    echo '<ul' . ($expanded ? ' class="expanded"' : '') . '><li>';
                }
                else {
                    echo '<li>';
                }

                if (empty($options['raw'])):
                    $query = [
                        'property' => [['property' => $referenceId, 'type' => $queryType, 'text' => $subject]],
                    ];
                    echo $this->hyperlink(
                        $subject,
                        $this->url('site/resource', ['controller' => $controllerName, 'action' => 'browse'], ['query' => $query], true)
                    );
                else:
                    echo $subject;
                endif;

                $previous_level = $level;
            }
            // Manage last liine.
            echo '</li>' . PHP_EOL . str_repeat('</ul></li>' . PHP_EOL, $previous_level);
        ?>
    </ul>
</div>
<?php endif;
