<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $terms
 * @var bool $totals
 * @var string $resourceName
 * @var array $args
 * @var string $type
 */

$translate = $this->plugin('translate');
$hyperlink = $this->plugin('hyperlink');
$url = $this->plugin('url');
$api = $this->api();
$siteSlug = $this->params()->fromRoute('site-slug');

$this->htmlElement('body')->appendAttribute('class', 'reference browse list');
?>
<ul class="references">
    <?php foreach ($terms as $term): ?>
    <li><?php
    // TODO Currently, the totals are determined one by one.
    if ($totals):
        // TODO Get the properties labels one time.
        $label = $api->searchOne($type, ['term' => $term])->getContent()->label();
        $total = $this->reference()->count($term, $type, $resourceName, $args['query']);
        echo $hyperlink(
            sprintf($translate('%s (%d)'), $label, $total),
            // TODO Define the link to the reference page.
            $url('site/page', ['site-slug' => $siteSlug, 'page-slug' => str_replace(':', '-', $term)]),
            ['title' => sprintf($translate('Browse %s'), $label)]
        );
    else:
        $label = $api->searchOne($type, ['term' => $term])->getContent()->label();
        $total = $this->reference()->count($term, $type, $resourceName, $args['query']);
        echo $hyperlink(
            $label,
            // TODO Define the link to the reference page.
            $url('site/page', ['site-slug' => $siteSlug, 'page-slug' => str_replace(':', '-', $term)]),
            ['title' => sprintf($translate('Browse %s'), $label)]
        );
    endif;
    ?>
    </li>
    <?php endforeach; ?>
</ul>
