<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var array $fields
 * @var array $query
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$easyMeta = $plugins->get('easyMeta');
$references = $plugins->get('references');

$siteSlug = $site->slug();

$totals = $references->count($fields, $query, $options);

$this->htmlElement('body')->appendAttribute('class', 'reference browse list');
?>

<ul class="references">
    <?php foreach ($fields['fields'] ?? [] as $field): ?>
    <li><?php
    $property = $easyMeta->propertyId($field);
    $class = $property ? $easyMeta->resourceClassId($field) : null;
    $label = $translate($class ? $easyMeta->resourceClassLabel($class) : $easyMeta->propertyLabel($property));
    $labelTotal = empty($options['total']) ? $label : sprintf($translate('%s (%d)'), $label, $totals[$field] ?? 0);
    echo $hyperlink(
        $labelTotal,
        $url('site/page', ['site-slug' => $siteSlug, 'page-slug' => strtr($field, [':' => '-'])]),
        ['title' => sprintf($translate('Browse %s'), $label)]
    );
    ?>
    </li>
    <?php endforeach; ?>
</ul>
