<?php
$resourceName = 'items';
$this->headLink()->prependStylesheet($this->assetUrl('css/reference.css', 'Reference'));
if (count($references)):
    $queryType = isset($options['query_type']) ? $options['query_type'] : 'eq';
    // Dublin Core Title is always 1.
    $referenceId = $slugData['type'] == 'properties' ? $slugData['id'] : 1;
    // Prepare and display skip links.
    if ($options['skiplinks']):
        // Get the list of headers.
        $letters = ['number' => false] + array_fill_keys(range('A', 'Z'), false);
        foreach ($references as $reference => $referenceData):
            $first_char = function_exists('mb_substr') ? mb_substr($reference, 0, 1) : substr($reference, 0, 1);
            if (strlen($first_char) == 0 || preg_match('/\W|\d/u', $first_char)):
                $letters['number'] = true;
            else:
                $letters[strtoupper($first_char)] = true;
            endif;
        endforeach;
        $pagination_list = '<ul class="pagination_list">';
        foreach ($letters as $letter => $isSet):
            $letterDisplay = $letter == 'number' ? '#0-9' : $letter;
            if ($isSet):
                $pagination_list .= sprintf('<li class="pagination_range"><a href="#%s">%s</a></li>', $letter, $letterDisplay);
            else:
                $pagination_list .= sprintf('<li class="pagination_range"><span>%s</span></li>', $letterDisplay);
            endif;
        endforeach;
        $pagination_list .= '</ul>';
    ?>
<div class="pagination reference-pagination" id="pagination-top">
    <?php echo $pagination_list; ?>
</div>
    <?php endif; ?>

<div id="reference-headings">
    <?php
    $linkSingle = !empty($options['link_single']);
    $current_heading = '';
    $current_id = '';
    foreach ($references as $reference => $referenceData):
        $referenceValue = is_null($referenceData['value']) ? '[Untitled]' : $referenceData['value'];
        // Add the first character as header if wanted.
        if ($options['headings']):
            $first_char = function_exists('mb_substr') ? mb_substr($reference, 0, 1) : substr($reference, 0, 1);
            if (strlen($first_char) == 0 || preg_match('/\W|\d/u', $first_char)) {
                $first_char = '#0-9';
            }
            $current_first_char = strtoupper($first_char);
            if ($current_heading !== $current_first_char):
                $current_heading = $current_first_char;
                $current_id = $current_heading === '#0-9' ? 'number' : $current_heading;
    ?>
    <h3 class="reference-heading" id="<?php echo $current_id; ?>"><?php echo $current_heading; ?></h3>
    <?php
            endif;
        endif;
    ?>

    <p class="reference-record">
        <?php if (empty($options['raw'])):
            if ($linkSingle && $referenceData['total'] === 1):
                $resource = $this->api()->read($resourceName, $referenceData['first_id'])->getContent();
                echo $this->hyperlink($referenceValue, $resource->siteUrl());
            else:
                $query = [
                    'property' => [['property' => $referenceId, 'type' => $queryType, 'text' => $reference]],
                ];
                if ($slugData['type'] == 'resource_classes'):
                    $query['resource_class_id'] = 26;
                endif;
                echo $this->hyperlink(
                    $referenceValue,
                    $this->url('site/resource', ['controller' => 'item', 'action' => 'browse'], ['query' => $query], true)
                );
                // Can be null when references are set directly.
                if ($referenceData['total']):
                    echo ' (' . $referenceData['total'] . ')';
                endif;
            endif;
        else:
            echo $reference;
        endif; ?>
    </p>
    <?php endforeach; ?>
</div>

    <?php if ($options['skiplinks']): ?>
<div class="pagination reference-pagination" id="pagination-bottom">
    <?php echo $pagination_list; ?>
</div>
    <?php endif;
endif;
