<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var string $heading
 * @var int $total
 * @var array $tree
 * @var string $query
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$references = $plugins->get('references');
?>

<div class="reference-block">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>
    <?php if ($total): ?>
    <?= $references->displayTree($tree, $query, $options) ?>
    <?php else: ?>
    <p><?= $translate('There is no references.') ?></p>
    <?php endif; ?>
</div>
