<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $term
 * @var array $query
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');

$total = $this->references()->count($term, $query, $options);
?>

<div class="reference-block">
    <?php if ($options['heading']): ?>
    <h3><?= $escape(str_replace('{total}', $total, $translate($options['heading']))) ?></h3>
    <?php endif; ?>
    <?php if ($total): ?>
    <?= $this->references()->displayListForTerm($term, $query, $options) ?>
    <?php else: ?>
    <p><?= $translate('There is no references.') ?></p>
    <?php endif; ?>
</div>
