<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var int $total
 * @var array $tree
 * @var string $query
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$references = $plugins->get('references');
?>

<div class="reference-block">
    <?php if ($total): ?>
    <?= $references->displayTree($tree, $query, $options) ?>
    <?php else: ?>
    <p><?= $translate('There is no references.') ?></p>
    <?php endif; ?>
</div>
