<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var array $terms
 * @var array $args
 * @var array $options
 * @var bool $totals
 */

$translate = $this->plugin('translate');
?>

<div class="reference-block">
    <?php if ($options['heading']): ?>
    <h3><?= $translate($options['heading']) ?></h3>
    <?php endif; ?>

    <?php if (empty($terms)): ?>
    <p><?= $translate('There is no references.') ?></p>
    <?php else: ?>
    <?php
    echo $this->partial('common/reference-index', [
        'site' => $block->page()->site(),
        'terms' => $terms,
        'type' => $args['type'],
        'resourceName' => $args['resource_name'],
        'totals' => $totals,
        'args' => $args,
        'options' => $options,
    ]);
    ?>
    <?php endif; ?>
</div>
