<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var array $fields
 * @var array $query
 * @var array $options
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeAttr');
$translate = $plugins->get('translate');
?>

<div class="reference-block">
    <?php if ($options['heading']): ?>
    <h2><?= $escape($options['heading']) ?></h2>
    <?php endif; ?>
    <?php if (empty($fields)): ?>
    <p><?= $translate('There is no references.') ?></p>
    <?php else: ?>
    <?= $this->partial('common/reference-index', [
        'site' => $block->page()->site(),
        'fields' => $fields,
        'query' => $query,
        'options' => $options,
    ]) ?>
    <?php endif; ?>
</div>
