<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'reference browse list');
$siteSlug = $this->params()->fromRoute('site-slug');
$resourceName = empty($resourceName) ? 'items' : $resourceName;
$query = empty($query) ? ['site_id' => $site->id()] : $query;
?>
<div id="primary" class="reference">
    <h2><?php echo $translate('References'); ?></h2>
    <?php if (empty($types)): ?>
        <p><?php echo $translate('No references available.'); ?></p>
    <?php else: ?>
        <?php
    if (count($types) == 1): ?>
        <ul class='references'>
        <?php foreach ($references as $slug => $slugData): ?>
            <li><?php
                echo $this->hyperlink(
                    sprintf('%s (%d)', $slugData['label'], $this->reference()->count($slugData['term'], $slugData['type'], $resourceName, $query)),
                    $this->url('site/reference/list', ['site-slug' => $siteSlug, 'slug' => $slug]),
                    ['title' => sprintf($translate('Browse %s'), $slugData['label'])]
                );
            ?>
            </li>
        <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <ul class='references'>
        <?php
        // References are ordered: Item Types, then Elements.
        $type = null;
        $first = true;
        foreach ($references as $slug => $slugData):
        $changedType = $slugData['type'] != $type;
            if ($changedType):
                if ($first):
                    $first = false;
                else: ?>
                    </ul></li>
                <?php endif; ?>
            <li><?php
                echo $slugData['type'] === 'resource_classes' ? $translate('Main types') : $translate('Metadata');
                $type = $slugData['type'];
            ?><ul>
            <?php endif; ?>
            <li><?php
                echo $this->hyperlink(
                    sprintf('%s (%d)', $slugData['label'], $this->reference()->count($slugData['term'], $slugData['type'], $resourceName, $query)),
                    $this->url('site/reference/list', ['site-slug' => $siteSlug, 'slug' => $slug]),
                    ['title' => sprintf($translate('Browse %s'), $slugData['label'])]
                );
            ?>
            </li>
        <?php endforeach; ?>
        </ul></li>
    <?php endif; ?>
    </ul>
    <?php endif; ?>
</div>
