<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'reference browse hierarchy');
?>
<div id="primary" class="reference">
    <h2><?php echo sprintf($this->translate('Hierarchy of Subjects (%d total)'), count($subjects)); ?></h2>
    <?php if (count($subjects)): ?>
    <?php
        echo $this->reference()->displayTree($subjects);
    ?>
    <?php else: ?>
    <p><?php echo $this->translate('There is no hierarchy of subjects.'); ?></p>
    <?php endif; ?>
</div>
